# config/secrets.yml

development:
    access_key_id: "AKIAJ77ZRLWI2PVMAJ7A"
    secret_access_key: "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"
    bucket: "jamdropz-dev"
test:
    access_key_id: "AKIAJ77ZRLWI2PVMAJ7A"
    secret_access_key: "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"
    bucket: "jamdropz-dev"
#production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
#  aws:
#    access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
#    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
#    s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>